2011-06-30 18:39:08,044 root         INFO     RxboxEngine Start
2011-06-30 18:39:08,044 InitState    INFO     State Machine: InitState Start
2011-06-30 18:39:09,534 SnapshotControl INFO     SnapshotControl Module Initialized
2011-06-30 18:39:09,763 BP           INFO     BP Module Initialized
2011-06-30 18:39:09,777 SPO2         INFO     SPO2 Module Initialized
2011-06-30 18:39:09,790 ECG          INFO     ECG Module Initialized
2011-06-30 18:39:10,876 VoIP         INFO     VoIP Module Initialized
2011-06-30 18:39:10,880 IM           INFO     IM Module Initialized
2011-06-30 18:39:10,902 InitState    ERROR    Load Perspective
2011-06-30 18:39:11,024 root         ERROR    Change State Error
Traceback (most recent call last):
  File "RxboxEngine.py", line 82, in change_state
    self.state.start()
  File "/host/Users/JE/Desktop/je/testrepo/TelehealthTest/States/InitState/__init__.py", line 86, in start
    stat= config.get('GENINFO', 'testscreen')
  File "/usr/lib/python2.7/ConfigParser.py", line 610, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'testscreen' in section: 'GENINFO'

2011-06-30 18:39:11,027 StandbyState INFO     State Machine: StandbyState Start
2011-06-30 18:39:13,445 StandbyState INFO     State Machine: StandbyState Stop
2011-06-30 18:39:13,446 DAQState     INFO     State Machine: DAQState Start
2011-06-30 18:39:13,536 DAQState     INFO     Session uuid = 324ddce6-a305-11e0-bd78-001de07757a5
2011-06-30 18:39:14,838 ECG          ERROR    DAQ Start Failed
Traceback (most recent call last):
  File "/host/Users/JE/Desktop/je/testrepo/TelehealthTest/Modules/ECG/__init__.py", line 180, in Start
    self.plotter = CPlotter(panel=self.plot_panel, mode='normal', sample_time=self.daqdur, plot_timelength=75.0/self.scale[3], cont=True, filterOn=self.filter, data=False, scale=self.scale)
AttributeError: 'ECG' object has no attribute 'scale'

2011-06-30 18:39:22,438 root         ERROR    Change State Error
Traceback (most recent call last):
  File "RxboxEngine.py", line 82, in change_state
    self.state.start()
  File "/host/Users/JE/Desktop/je/testrepo/TelehealthTest/States/DAQState/__init__.py", line 35, in start
    self._panel['spo2'].Start()
  File "/host/Users/JE/Desktop/je/testrepo/TelehealthTest/Modules/SPO2/__init__.py", line 28, in Start
    port=c.check()
  File "/host/Users/JE/Desktop/je/testrepo/TelehealthTest/Modules/SPO2/spo2_portcheck.py", line 12, in check
    self.spo2 = SPO2DAQ(self,port =x,timeout=1)
  File "/host/Users/JE/Desktop/je/testrepo/TelehealthTest/Modules/SPO2/SPO2DAQLive.py", line 36, in __init__
    self.send_request()
  File "/host/Users/JE/Desktop/je/testrepo/TelehealthTest/Modules/SPO2/SPO2DAQLive.py", line 58, in send_request
    self.reset()
  File "/host/Users/JE/Desktop/je/testrepo/TelehealthTest/Modules/SPO2/SPO2DAQLive.py", line 64, in reset
    self.SerPort.flushInput()
AttributeError: SPO2DAQ instance has no attribute 'SerPort'

2011-06-30 18:39:22,439 StandbyState INFO     State Machine: StandbyState Start
2011-06-30 18:39:30,007 StandbyState INFO     State Machine: StandbyState Stop
2011-06-30 18:39:30,007 DAQState     INFO     State Machine: DAQState Start
2011-06-30 18:39:30,022 DAQState     INFO     Session uuid = 3c232276-a305-11e0-bd78-001de07757a5
2011-06-30 18:39:31,033 ECG          ERROR    DAQ Start Failed
Traceback (most recent call last):
  File "/host/Users/JE/Desktop/je/testrepo/TelehealthTest/Modules/ECG/__init__.py", line 180, in Start
    self.plotter = CPlotter(panel=self.plot_panel, mode='normal', sample_time=self.daqdur, plot_timelength=75.0/self.scale[3], cont=True, filterOn=self.filter, data=False, scale=self.scale)
AttributeError: 'ECG' object has no attribute 'scale'

